### ISSUE TITLE
How do you deal with the cases when the input is longer than the context length?

### ISSUE THREAD

**Issue by leoozy** [THUDM/AgentBench#48]
Hello, thank you for your code. I have some problems about your framework. In some tasks, such as webshop, the observation/history could be vary long, even longer than the context length of 4096. How do you deal with it? Thank you!

**Comment by Longin-Yu** [comment]
Thanks for you instrest. We have two operations for handling context limit.

1. **Omit earlier messages before inference.**  For take possibly more models into evaluation, we cut messages if too long, and keep the first and the latest ones. You can refer to [this piece of code](https://github.com/THUDM/AgentBench/blob/main/src/server/task.py#L112). After this step, tokens can be controlled within about 4k.
2. **Special judge for HTTPAgent.** Because earlier models (e.g. openai davinci) support 2k tokens only, we add [a special judge function](https://github.com/THUDM/AgentBench/blob/main/src/client/agents/http_agent.py#L138) for it.

**Comment by Xiao9905** [comment]
@leoozy Hi, thanks for your interest in AgentBench! Has your problem been solved successfully? Please feel free to reopen the issue for help if you need it.
