### ISSUE TITLE
[Bug/Assistance] document on v0.2

### ISSUE THREAD

**Issue by nlpcat** [THUDM/AgentBench#55]
It seems like we can't run the step by step installation and tests anymore since v0.2. For example, the requirements.txt doesn't cover the package needed by the code `fschat` and `antropic`. Any new document reference for this new version? And how can we build the docker image? thanks

**Comment by nlpcat** [comment]
@Longin-Yu

**Comment by Longin-Yu** [comment]
Really thanks for pointing this out! We have fixed this problem.

**Comment by nlpcat** [comment]
@Longin-Yu it seems like I also can't find the documentation that would include the docker image build `python src/server/tasks/os_interaction/images.py build -c configs/tasks/os.yaml -r .
` for v0.2. in addition, images.py is broken that needs a small fix to point out to use`os-std` or `os-dev`

**Comment by Longin-Yu** [comment]
In v0.2, the images.py file has been deprecated, and we recommend [building the images directly](https://github.com/THUDM/AgentBench#step-1-prerequisites). Another advantage of this approach is that it allows for easier bug localization in cases where issues arise due to network or environmental factors.
